# Generated by Django 5.0.2 on 2024-02-19 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_teste', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bancodados',
            name='nascimento',
        ),
    ]
